# Generated by Django 2.1.1 on 2020-02-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200210_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expire',
            field=models.IntegerField(default=1),
        ),
    ]
