# Generated by Django 2.1.1 on 2020-02-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
    ]
